source 'https://github.com/CocoaPods/Specs.git'


target 'AFAmazonS3Manager', :exclusive => true do
  pod "AFAmazonS3Manager", :path => "../"
  pod 'OCMock', '~> 3.1.2'
  pod 'Expecta', '~> 0.4.0'
end
